#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width        	1
bspc config window_gap         		7
bspc config border_radius		20
bspc config split_ratio          	0.50

### Prefs
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config history_aware_focus         true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

### Outer margins
bspc config bottom_padding		4
bspc config top_padding			24
bspc config right_padding		4
bspc config left_padding 		4

### Colors
bspc config focused_border_color "#4ff6ff"

### Rules
bspc rule -a Galculator state=floating
bspc rule -a Zathura state=tiled

### Wallpaper
feh --bg-fill Pictures/wallpapers/from-mac/wallpaper1.jpg
#hsetroot -solid '#375eab'

### Startup
wmname LG3D
./.config/polybar/launch.sh 
picom &
nm-applet&
kdeconnect-indicator &
blueman-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
